export const images={
    match_master_onboard:require("../pngs/match_master_onboard.png"),
    stay_updated_onboard:require("../pngs/stay_updated_onboard.png"),
    team_onboard:require("../pngs/team_onboard.png"),
    next_arrow:require("../pngs/next_arrow.png"),
    logo:require("../pngs/logo.png"),
    state_up:require("../pngs/state_up.png"),
    down:require("../pngs/down.png"),
    mask:require("../pngs/mask.png"),
    home:require("../pngs/home.png"),
    filled_home:require("../pngs/filled_home.png"),
    vip:require("../pngs/vip.png"),
    filled_vip:require("../pngs/vip.png"),
    by_game:require("../pngs/by_game.png"),
    following_users:require("../pngs/following_users.png"),
    basketball:require("../pngs/basketball.png"),
    soccer:require("../pngs/soccer.png"),
    feed:require("../pngs/feed.png"),
    user1:require("../pngs/user1.png"),
    user2:require("../pngs/user2.png"),
    user3:require("../pngs/user3.png"),
    user4:require("../pngs/user4.png"),

    profile_placeholder:require("../pngs/profile_placeholder.png"),
    tennis:require("../pngs/tennis.png"),
    volleyball:require("../pngs/volleyball.png"),
    cricket:require("../pngs/cricket.png"),
    handball:require("../pngs/handball.png"),
    user_stories:require("../pngs/user_stories.png"),
    best_beat:require("../pngs/best_beat.png"),
    players:require("../pngs/players.png"),
    pro_img:require("../pngs/pro_img.png"),
    tap_ball:require("../pngs/tap_ball.png"),
    notification:require("../pngs/notification.png"),
    leagues:require("../pngs/leagues.png"),
    trophy:require("../pngs/trophy.png"),
    next:require("../pngs/next.png"),
    search:require("../pngs/search.png"),
    plus:require("../pngs/plus.png"),
    down_gray:require("../pngs/down_gray.png"),

    eV_calculator:require("../pngs/eV_calculator.png"),
    bet_calculator:require("../pngs/bet_calculator.png"),
    odds_converter:require("../pngs/odds_converter.png"),
    margin_calculator:require("../pngs/margin_calculator.png"),
    arb_calculator:require("../pngs/arb_calculator.png"),
    cle:require("../pngs/cle.png"),
    cle_12:require("../pngs/cle_12.png"),
    calendar:require("../pngs/calendar.png"),
    filter:require("../pngs/filter.png"),
    left_arrow:require("../pngs/left_arrow.png"),
    up_arrow:require("../pngs/up_arrow.png"),

    tracks:require("../pngs/tracks.png"),
    back:require("../pngs/back.png"),
    pause:require("../pngs/pause.png"),
    episode:require("../pngs/episode.png"),
    img_placeholder:require("../pngs/img_placeholder.png"),
    sports:require("../pngs/sports.png"),
    boxes:require("../pngs/boxes.png"),
    filled_feed:require("../pngs/filled_feed.png"),
    top_game:require("../pngs/top_game.png"),
    profile:require("../pngs/profile.png"),
    filled_profile:require("../pngs/filled_profile.png"),



    users:require("../pngs/users.png"),
    message:require("../pngs/message.png"),
    lock:require("../pngs/lock.png"),
    info:require("../pngs/info.png"),
    google:require("../pngs/google.png"),
    facebook:require("../pngs/facebook.png"),
    apple:require("../pngs/apple.png"),
    ball:require("../pngs/ball.png"),
    mem:require("../pngs/mem.png"),
    birds:require("../pngs/birds.png"),

    
    



}